---
- name: Install the latest version of yum-utils, curl
  yum:
    name:
      - yum-utils
      - curl
      - epel-release
    state: latest

- name: Add repository
  yum_repository:
    name: docker-ce
    description: Docker CE repo
    baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/

- name: Install docker-ce
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    disable_gpg_check: yes

- name: Install docker-compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Make docker-compose executable
  file:
    path: /usr/local/bin/docker-compose
    mode: '0755'

- name: Link docker-compose
  file:
    state: link
    path: /usr/bin/docker-compose
    src: /usr/local/bin/docker-compose

# EOF